plugins:
  - jekyll-remote-theme
  - jekyll-sitemap


remote_theme: heiswayi/the-plain
logo_url: https://github.com/lisa-wm/consulting/blob/main/5_seminar/Logo_Consulting.JPG
title: "Intro to NLP with R \& Python for Twitter data"
